//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEGv8Day {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LEGv8Day.ProgramData", typeof(ProgramData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Mnemonic,Format,OpCode
        ///ADD,ADD,R,458
        ///ADD Immediate,ADDI,I,488-489
        ///ADD Immediate &amp; Set flags,ADDIS,I,588-589
        ///ADD &amp; Set flags,ADDS,R,558
        ///AND,AND,R,450
        ///AND Immediate,ANDI,I,490-491
        ///AND Immediate &amp; Set flags,ANDIS,I,790-791
        ///AND &amp; Set flags,ANDS,R,750
        ///Branch,B,B,0A0-0BF
        ///Branch to Register,BR,R,6B0
        ///Compare &amp; Branch if Not Zero,CBNZ,CB,5A8-5AF
        ///Compare &amp; Branch if Zero,CBZ,CB,5A0-5A7
        ///Exclusive OR,EOR,R,650
        ///Exclusive OR Immediate,EORI,I,690-691
        ///LoaD Register Unscaled offset,LDUR,D,7C2
        ///LoaD Byte  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoreInstructions {
            get {
                return ResourceManager.GetString("CoreInstructions", resourceCulture);
            }
        }
    }
}
